### ISSUE TITLE
Migrate content: events

### ISSUE THREAD

**Issue by finnlewis** [IIED-org/pubs#127]

**Comment by finnlewis** [comment]
On dev-master ready for test. 

After running locally: 

```
  IIED Drupal 7 Migrations (iied_migrate_d7)   iied_d7_events                                      Idle     159     159        0             2022-02-09 15:31:19  
```

**Comment by finnlewis** [comment]
Hi @cbrody 
Good catch, sorry! 
This PR should rectify the situation: https://github.com/IIED-org/pubs/pull/161
The field is getting migrated for me locally now.

**Comment by cbrody** [comment]
End date not required to be migrated but will need field_end_date on the Event content type.

**Comment by cbrody** [comment]
The migrated field_date has been created as a date-only field, but I believe we'll need a date+time field going forward. An option is to use a separate daterange field with both start and end date/time subfields, but this requires an additional [module] (https://www.drupal.org/project/optional_end_date) in order to make the end date/time optional. @ncktrnr @finnlewis @mattjobob your thoughts?

**Comment by cbrody** [comment]
A suggestion is to have a new date-time daterange field with optional end date, and use a separate field for any additional info e.g. clarification of time zone or a flexible end time.

**Comment by cbrody** [comment]
Agreed to have datetime daterange field with optional end date but only display date (without time), using the time textfield to specify times in the desired format. 
![image](https://user-images.githubusercontent.com/511131/169497518-5ea15afd-0134-4c3a-8b53-5367ea10ac62.png)

**Comment by cbrody** [comment]
Forgot to give the branch: #feature/127-migrate-events

**Comment by cbrody** [comment]
Looks good now, closing.
